/**
 * ABOUTME: Extracts video info and caption tracks from YouTube Innertube player responses.
 * ABOUTME: Used by the content script to parse responses from the Innertube ANDROID API.
 */

import type { VideoInfo, CaptionTrack, Chapter } from '../../core/types';

/* eslint-disable @typescript-eslint/no-explicit-any */

export function extractVideoInfo(playerResponse: any): VideoInfo | null {
  const details = playerResponse?.videoDetails;
  if (!details) return null;

  return {
    videoId: details.videoId,
    title: details.title,
    channelName: details.author ?? '',
    durationMs: parseInt(details.lengthSeconds, 10) * 1000,
  };
}

/** Recursively collect all values for a given key at any depth. */
function findAllByKey(obj: any, targetKey: string): any[] {
  const results: any[] = [];
  if (obj == null || typeof obj !== 'object') return results;
  for (const key of Object.keys(obj)) {
    if (key === targetKey) results.push(obj[key]);
    results.push(...findAllByKey(obj[key], targetKey));
  }
  return results;
}

export function extractChapters(nextResponse: any): Chapter[] {
  const markers = findAllByKey(nextResponse, 'macroMarkersListItemModel');
  const chapters: Chapter[] = [];
  for (const marker of markers) {
    const renderer = marker?.renderer;
    if (!renderer) continue;
    const title = renderer.title?.elementsAttributedString?.content;
    const startSeconds =
      renderer.onTap?.commandExecutorCommand?.commands?.[0]?.watchEndpoint?.startTimeSeconds;
    if (title != null && startSeconds != null) {
      chapters.push({ title, startTimeMs: startSeconds * 1000 });
    }
  }
  return chapters.sort((a, b) => a.startTimeMs - b.startTimeMs);
}

export function extractCaptionTracks(playerResponse: any): CaptionTrack[] {
  const trackList = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(trackList)) return [];

  return trackList.map((track: any) => {
    let baseUrl = track.baseUrl ?? '';
    // Replace any existing fmt parameter (e.g., fmt=srv3 from ANDROID client) with json3
    if (baseUrl.includes('fmt=')) {
      baseUrl = baseUrl.replace(/fmt=[^&]*/, 'fmt=json3');
    } else {
      baseUrl += (baseUrl.includes('?') ? '&' : '?') + 'fmt=json3';
    }

    return {
      languageCode: track.languageCode ?? '',
      languageName: track.name?.simpleText ?? track.languageCode ?? '',
      baseUrl,
      isAutoGenerated: track.kind === 'asr',
    };
  });
}
