/**
 * ABOUTME: Extracts video info and caption tracks from YouTube's ytInitialPlayerResponse.
 * ABOUTME: Used by the content script to discover available captions for a video.
 */

import type { VideoInfo, CaptionTrack } from '../../core/types';

/* eslint-disable @typescript-eslint/no-explicit-any */

export function extractVideoInfo(playerResponse: any): VideoInfo | null {
  const details = playerResponse?.videoDetails;
  if (!details) return null;

  return {
    videoId: details.videoId,
    title: details.title,
    channelName: details.author ?? '',
    durationMs: parseInt(details.lengthSeconds, 10) * 1000,
  };
}

export function extractCaptionTracks(playerResponse: any): CaptionTrack[] {
  const trackList = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(trackList)) return [];

  return trackList.map((track: any) => {
    let baseUrl = track.baseUrl ?? '';
    if (!baseUrl.includes('fmt=json3')) {
      baseUrl += (baseUrl.includes('?') ? '&' : '?') + 'fmt=json3';
    }

    return {
      languageCode: track.languageCode ?? '',
      languageName: track.name?.simpleText ?? track.languageCode ?? '',
      baseUrl,
      isAutoGenerated: track.kind === 'asr',
    };
  });
}

export function extractPlayerResponseFromHtml(html: string): any | null {
  const match = html.match(/ytInitialPlayerResponse\s*=\s*({.+?})\s*;/);
  if (!match) return null;

  try {
    return JSON.parse(match[1]);
  } catch {
    return null;
  }
}
