import { describe, it, expect } from 'vitest';
import { extractVideoInfo, extractCaptionTracks } from '../../../src/adapters/youtube/innertube';
import fixture from '../../fixtures/youtube-pages/sample-player-response.json';

describe('extractVideoInfo', () => {
  it('should extract video info from player response', () => {
    const info = extractVideoInfo(fixture);
    expect(info).not.toBeNull();
    expect(info!.videoId).toBe('YwZR6tc7qYg');
    expect(info!.title).toBe('Everything We Got Wrong About Research-Plan-Implement');
    expect(info!.channelName).toBe('Test Channel');
    expect(info!.durationMs).toBe(2723000);
  });

  it('should return null for missing videoDetails', () => {
    expect(extractVideoInfo({})).toBeNull();
  });
});

describe('extractCaptionTracks', () => {
  it('should extract caption tracks from player response', () => {
    const tracks = extractCaptionTracks(fixture);
    expect(tracks.length).toBe(2);
    expect(tracks[0].languageCode).toBe('en');
    expect(tracks[0].isAutoGenerated).toBe(true);
    expect(tracks[0].baseUrl).toContain('timedtext');
    expect(tracks[1].languageCode).toBe('es');
    expect(tracks[1].isAutoGenerated).toBe(false);
  });

  it('should return empty array for missing captions', () => {
    expect(extractCaptionTracks({})).toEqual([]);
  });

  it('should ensure baseUrl includes fmt=json3', () => {
    const tracks = extractCaptionTracks(fixture);
    for (const track of tracks) {
      expect(track.baseUrl).toContain('fmt=json3');
    }
  });
});
