import { describe, it, expect } from 'vitest';
import {
  extractVideoInfo,
  extractCaptionTracks,
  extractChapters,
} from '../../../src/adapters/youtube/innertube';
import fixture from '../../fixtures/youtube-pages/sample-player-response.json';
import nextFixture from '../../fixtures/youtube-pages/sample-next-response.json';

describe('extractVideoInfo', () => {
  it('should extract video info from player response', () => {
    const info = extractVideoInfo(fixture);
    expect(info).not.toBeNull();
    expect(info!.videoId).toBe('YwZR6tc7qYg');
    expect(info!.title).toBe('Everything We Got Wrong About Research-Plan-Implement');
    expect(info!.channelName).toBe('Test Channel');
    expect(info!.durationMs).toBe(2723000);
  });

  it('should return null for missing videoDetails', () => {
    expect(extractVideoInfo({})).toBeNull();
  });
});

describe('extractCaptionTracks', () => {
  it('should extract caption tracks from player response', () => {
    const tracks = extractCaptionTracks(fixture);
    expect(tracks.length).toBe(2);
    expect(tracks[0].languageCode).toBe('en');
    expect(tracks[0].isAutoGenerated).toBe(true);
    expect(tracks[0].baseUrl).toContain('timedtext');
    expect(tracks[1].languageCode).toBe('es');
    expect(tracks[1].isAutoGenerated).toBe(false);
  });

  it('should return empty array for missing captions', () => {
    expect(extractCaptionTracks({})).toEqual([]);
  });

  it('should ensure baseUrl includes fmt=json3', () => {
    const tracks = extractCaptionTracks(fixture);
    for (const track of tracks) {
      expect(track.baseUrl).toContain('fmt=json3');
    }
  });

  it('should replace existing fmt parameter with json3', () => {
    const response = {
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              baseUrl: 'https://www.youtube.com/api/timedtext?v=test&fmt=srv3&lang=en',
              languageCode: 'en',
              name: { simpleText: 'English' },
            },
          ],
        },
      },
    };
    const tracks = extractCaptionTracks(response);
    expect(tracks[0].baseUrl).toContain('fmt=json3');
    expect(tracks[0].baseUrl).not.toContain('fmt=srv3');
  });
});

describe('extractChapters', () => {
  it('extracts chapters from /next response', () => {
    const chapters = extractChapters(nextFixture);
    expect(chapters).toHaveLength(3);
    expect(chapters[0]).toEqual({ title: 'Intro', startTimeMs: 0 });
    expect(chapters[1]).toEqual({ title: 'Main Topic', startTimeMs: 90000 });
    expect(chapters[2]).toEqual({ title: 'Conclusion', startTimeMs: 300000 });
  });

  it('returns empty array when no chapters exist', () => {
    expect(extractChapters({})).toEqual([]);
  });

  it('returns empty array for null/undefined input', () => {
    expect(extractChapters(null)).toEqual([]);
    expect(extractChapters(undefined)).toEqual([]);
  });
});
