/**
 * ABOUTME: Tests for the YouTubeTranscriptSource adapter.
 * ABOUTME: Verifies Innertube API calls and response parsing via injected fetch mock.
 */
import { describe, it, expect, vi } from 'vitest';
import { YouTubeTranscriptSource } from '../../../src/adapters/youtube/transcript-source';
import playerResponseFixture from '../../fixtures/youtube-pages/sample-player-response.json';
import autoCaptionsFixture from '../../fixtures/captions/sample-auto-captions.json';

function makeFetch(responseData: unknown, ok = true): typeof fetch {
  return vi.fn().mockResolvedValue({
    ok,
    json: vi.fn().mockResolvedValue(responseData),
  }) as unknown as typeof fetch;
}

describe('YouTubeTranscriptSource constructor', () => {
  it('default fetchFn does not lose the window.fetch binding', async () => {
    // Reproduces the "Illegal invocation" bug: when fetch is stored as a plain
    // property and called via `this.fetchFn(...)`, it can lose its window
    // binding. The fix wraps fetch in an arrow function.
    const globalFetch = vi.fn().mockImplementation(function (this: unknown) {
      // Simulate browser's strict this-check. Chrome's fetch throws if
      // called without being bound to window.
      if (this !== undefined && this !== globalThis) {
        throw new TypeError("Failed to execute 'fetch' on 'Window': Illegal invocation");
      }
      return Promise.resolve({
        ok: true,
        json: () => Promise.resolve({}),
      });
    });
    const originalFetch = globalThis.fetch;
    globalThis.fetch = globalFetch as unknown as typeof fetch;
    try {
      // Construct without passing fetchFn, forcing use of the default
      const source = new YouTubeTranscriptSource();
      // This would throw "Illegal invocation" if the binding is lost
      await expect(source.getVideoMetadata('abc123')).resolves.toBeDefined();
    } finally {
      globalThis.fetch = originalFetch;
    }
  });
});

describe('YouTubeTranscriptSource.getVideoMetadata', () => {
  it('calls Innertube ANDROID API with correct URL, method, headers, and body', async () => {
    const mockFetch = makeFetch(playerResponseFixture);
    const source = new YouTubeTranscriptSource(mockFetch);

    await source.getVideoMetadata('YwZR6tc7qYg');

    expect(mockFetch).toHaveBeenCalledOnce();
    const [url, options] = (mockFetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toBe('https://www.youtube.com/youtubei/v1/player?prettyPrint=false');
    expect(options.method).toBe('POST');
    expect(options.headers['Content-Type']).toBe('application/json');
    expect(options.headers['User-Agent']).toContain('com.google.android.youtube');
    const body = JSON.parse(options.body);
    expect(body.videoId).toBe('YwZR6tc7qYg');
    expect(body.context.client.clientName).toBe('ANDROID');
  });

  it('makes only one fetch call for both videoInfo and captionTracks', async () => {
    const mockFetch = makeFetch(playerResponseFixture);
    const source = new YouTubeTranscriptSource(mockFetch);

    await source.getVideoMetadata('YwZR6tc7qYg');

    expect(mockFetch).toHaveBeenCalledOnce();
  });

  it('returns parsed video info from a successful response', async () => {
    const source = new YouTubeTranscriptSource(makeFetch(playerResponseFixture));
    const { videoInfo } = await source.getVideoMetadata('YwZR6tc7qYg');
    expect(videoInfo).not.toBeNull();
    expect(videoInfo!.videoId).toBe('YwZR6tc7qYg');
    expect(videoInfo!.title).toBe('Everything We Got Wrong About Research-Plan-Implement');
    expect(videoInfo!.channelName).toBe('Test Channel');
    expect(videoInfo!.durationMs).toBe(2723000);
  });

  it('returns caption tracks from a successful response', async () => {
    const source = new YouTubeTranscriptSource(makeFetch(playerResponseFixture));
    const { captionTracks } = await source.getVideoMetadata('YwZR6tc7qYg');
    expect(captionTracks.length).toBe(2);
    expect(captionTracks[0].languageCode).toBe('en');
    expect(captionTracks[0].isAutoGenerated).toBe(true);
    expect(captionTracks[0].baseUrl).toContain('fmt=json3');
    expect(captionTracks[1].languageCode).toBe('es');
  });

  it('returns null videoInfo and empty tracks when fetch response is not ok', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}, false));
    const { videoInfo, captionTracks } = await source.getVideoMetadata('bad-id');
    expect(videoInfo).toBeNull();
    expect(captionTracks).toEqual([]);
  });

  it('returns null videoInfo when player response has no videoDetails', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}));
    const { videoInfo } = await source.getVideoMetadata('YwZR6tc7qYg');
    expect(videoInfo).toBeNull();
  });

  it('returns empty tracks when player response has no captions', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}));
    const { captionTracks } = await source.getVideoMetadata('YwZR6tc7qYg');
    expect(captionTracks).toEqual([]);
  });
});

describe('YouTubeTranscriptSource.fetchTranscript', () => {
  const englishTrack = {
    languageCode: 'en',
    languageName: 'English',
    baseUrl: 'https://www.youtube.com/api/timedtext?v=test&fmt=json3',
    isAutoGenerated: true,
  };

  it('fetches caption JSON3 from the track baseUrl', async () => {
    const mockFetch = makeFetch(autoCaptionsFixture);
    const source = new YouTubeTranscriptSource(mockFetch);

    await source.fetchTranscript(englishTrack);

    expect(mockFetch).toHaveBeenCalledOnce();
    const [url] = (mockFetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toBe(englishTrack.baseUrl);
  });

  it('returns parsed TimedWord array from JSON3 caption data', async () => {
    const source = new YouTubeTranscriptSource(makeFetch(autoCaptionsFixture));
    const words = await source.fetchTranscript(englishTrack);
    expect(Array.isArray(words)).toBe(true);
    expect(words.length).toBeGreaterThan(0);
    expect(words[0]).toHaveProperty('text');
    expect(words[0]).toHaveProperty('start');
    expect(words[0]).toHaveProperty('end');
  });

  it('returns empty array when fetch fails', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}, false));
    const words = await source.fetchTranscript(englishTrack);
    expect(words).toEqual([]);
  });

  it('returns empty array when JSON3 has no events', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({ events: [] }));
    const words = await source.fetchTranscript(englishTrack);
    expect(words).toEqual([]);
  });
});
