/**
 * ABOUTME: Tests for the YouTubeTranscriptSource adapter.
 * ABOUTME: Verifies Innertube API calls and response parsing via injected fetch mock.
 */
import { describe, it, expect, vi } from 'vitest';
import { YouTubeTranscriptSource } from '../../../src/adapters/youtube/transcript-source';
import playerResponseFixture from '../../fixtures/youtube-pages/sample-player-response.json';
import autoCaptionsFixture from '../../fixtures/captions/sample-auto-captions.json';

function makeFetch(responseData: unknown, ok = true): typeof fetch {
  return vi.fn().mockResolvedValue({
    ok,
    json: vi.fn().mockResolvedValue(responseData),
  }) as unknown as typeof fetch;
}

describe('YouTubeTranscriptSource.getVideoInfo', () => {
  it('calls Innertube ANDROID API with correct URL, method, headers, and body', async () => {
    const mockFetch = makeFetch(playerResponseFixture);
    const source = new YouTubeTranscriptSource(mockFetch);

    await source.getVideoInfo('YwZR6tc7qYg');

    expect(mockFetch).toHaveBeenCalledOnce();
    const [url, options] = (mockFetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toBe('https://www.youtube.com/youtubei/v1/player?prettyPrint=false');
    expect(options.method).toBe('POST');
    expect(options.headers['Content-Type']).toBe('application/json');
    expect(options.headers['User-Agent']).toContain('com.google.android.youtube');
    const body = JSON.parse(options.body);
    expect(body.videoId).toBe('YwZR6tc7qYg');
    expect(body.context.client.clientName).toBe('ANDROID');
  });

  it('returns parsed video info from a successful response', async () => {
    const source = new YouTubeTranscriptSource(makeFetch(playerResponseFixture));
    const info = await source.getVideoInfo('YwZR6tc7qYg');
    expect(info).not.toBeNull();
    expect(info!.videoId).toBe('YwZR6tc7qYg');
    expect(info!.title).toBe('Everything We Got Wrong About Research-Plan-Implement');
    expect(info!.channelName).toBe('Test Channel');
    expect(info!.durationMs).toBe(2723000);
  });

  it('returns null when fetch response is not ok', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}, false));
    const info = await source.getVideoInfo('bad-id');
    expect(info).toBeNull();
  });

  it('returns null when player response has no videoDetails', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}));
    const info = await source.getVideoInfo('YwZR6tc7qYg');
    expect(info).toBeNull();
  });
});

describe('YouTubeTranscriptSource.getCaptionTracks', () => {
  it('calls Innertube ANDROID API with correct params', async () => {
    const mockFetch = makeFetch(playerResponseFixture);
    const source = new YouTubeTranscriptSource(mockFetch);

    await source.getCaptionTracks('YwZR6tc7qYg');

    expect(mockFetch).toHaveBeenCalledOnce();
    const [url, options] = (mockFetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toBe('https://www.youtube.com/youtubei/v1/player?prettyPrint=false');
    const body = JSON.parse(options.body);
    expect(body.videoId).toBe('YwZR6tc7qYg');
    expect(body.context.client.clientName).toBe('ANDROID');
  });

  it('returns caption tracks from a successful response', async () => {
    const source = new YouTubeTranscriptSource(makeFetch(playerResponseFixture));
    const tracks = await source.getCaptionTracks('YwZR6tc7qYg');
    expect(tracks.length).toBe(2);
    expect(tracks[0].languageCode).toBe('en');
    expect(tracks[0].isAutoGenerated).toBe(true);
    expect(tracks[0].baseUrl).toContain('fmt=json3');
    expect(tracks[1].languageCode).toBe('es');
  });

  it('returns empty array when fetch response is not ok', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}, false));
    const tracks = await source.getCaptionTracks('bad-id');
    expect(tracks).toEqual([]);
  });

  it('returns empty array when player response has no captions', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}));
    const tracks = await source.getCaptionTracks('YwZR6tc7qYg');
    expect(tracks).toEqual([]);
  });
});

describe('YouTubeTranscriptSource.fetchTranscript', () => {
  const englishTrack = {
    languageCode: 'en',
    languageName: 'English',
    baseUrl: 'https://www.youtube.com/api/timedtext?v=test&fmt=json3',
    isAutoGenerated: true,
  };

  it('fetches caption JSON3 from the track baseUrl', async () => {
    const mockFetch = makeFetch(autoCaptionsFixture);
    const source = new YouTubeTranscriptSource(mockFetch);

    await source.fetchTranscript(englishTrack);

    expect(mockFetch).toHaveBeenCalledOnce();
    const [url] = (mockFetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toBe(englishTrack.baseUrl);
  });

  it('returns parsed TimedWord array from JSON3 caption data', async () => {
    const source = new YouTubeTranscriptSource(makeFetch(autoCaptionsFixture));
    const words = await source.fetchTranscript(englishTrack);
    expect(Array.isArray(words)).toBe(true);
    expect(words.length).toBeGreaterThan(0);
    expect(words[0]).toHaveProperty('text');
    expect(words[0]).toHaveProperty('start');
    expect(words[0]).toHaveProperty('end');
  });

  it('returns empty array when fetch fails', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({}, false));
    const words = await source.fetchTranscript(englishTrack);
    expect(words).toEqual([]);
  });

  it('returns empty array when JSON3 has no events', async () => {
    const source = new YouTubeTranscriptSource(makeFetch({ events: [] }));
    const words = await source.fetchTranscript(englishTrack);
    expect(words).toEqual([]);
  });
});
