import { describe, it, expect } from 'vitest';
import type { TimedWord, VideoInfo, CaptionTrack } from '../../../src/core/types';

describe('core types', () => {
  it('should create a TimedWord', () => {
    const word: TimedWord = {
      text: 'hello',
      start: 0,
      end: 500,
      original: 'hello',
    };
    expect(word.text).toBe('hello');
    expect(word.start).toBe(0);
    expect(word.end).toBe(500);
  });

  it('should create a VideoInfo', () => {
    const info: VideoInfo = {
      videoId: 'abc123',
      title: 'Test Video',
      channelName: 'Test Channel',
      durationMs: 120000,
    };
    expect(info.videoId).toBe('abc123');
    expect(info.title).toBe('Test Video');
    expect(info.channelName).toBe('Test Channel');
    expect(info.durationMs).toBe(120000);
  });

  it('should create a CaptionTrack', () => {
    const track: CaptionTrack = {
      languageCode: 'en',
      languageName: 'English',
      baseUrl: 'https://example.com/captions',
      isAutoGenerated: true,
    };
    expect(track.languageCode).toBe('en');
    expect(track.languageName).toBe('English');
    expect(track.baseUrl).toBe('https://example.com/captions');
    expect(track.isAutoGenerated).toBe(true);
  });
});
