/**
 * ABOUTME: Core data types for transcript representation.
 * ABOUTME: Used across all layers of the application.
 */

export interface TimedWord {
  text: string;
  start: number;
  end: number;
  original: string;
}

export interface VideoInfo {
  videoId: string;
  title: string;
  channelName: string;
  durationMs: number;
}

export interface Chapter {
  title: string;
  startTimeMs: number;
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  isAutoGenerated: boolean;
}
